//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tour_doan
    {
        public int doan_id { get; set; }

        [Required]
        [Display(Name = "Tour")]
        public int tour_id { get; set; }

        [Required]
        [Display(Name = "Tên đoàn")]
        public string doan_name { get; set; }

        [Required]
        [Display(Name = "Ngày đi"), DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime doan_ngaydi { get; set; }

        [Required]
        [Display(Name = "Ngày về"), DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime doan_ngayve { get; set; }

        [Required]
        [Display(Name = "Mô tả chuyến đi")]
        public string doan_chitietchuongtrinh { get; set; }

        [Required]
        [Display(Name = "Giá Tour")]
        public int gia_id { get; set; }
    }
}
