//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tour_chiphi
    {
        public int chiphi_id { get; set; }

        [Required]
        [Display(Name = "Đoàn")]
        public int doan_id { get; set; }

        [Display(Name = "Tổng chi phí")]
        public double chiphi_total { get; set; }

        
        [Display(Name = "Chi tiết")]
        public string chiphi_chitiet { get; set; }
    }
}
