//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tour_loaichiphi
    {
        public int cp_id { get; set; }

        [Required]
        [Display(Name = "Tên Loại chi phí")]
        public string cp_ten { get; set; }

        [Required]
        [Display(Name = "Mô tả Loại chi phí")]
        public string cp_mota { get; set; }
    }
}
