//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tour_nhanvien
    {
		[Display(Name = "Mã NV")]
        public int nv_id { get; set; }

        [Required]
        [Display(Name = "Họ và tên")]
        public string nv_ten { get; set; }

        [Required]
        [Display(Name = "Số điện thoại")]
        public string nv_sdt { get; set; }

        [Required]
        [Display(Name = "Ngày sinh"), DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime nv_ngaysinh { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string nv_email { get; set; }

        [Required]
        [Display(Name = "Nhiệm vụ")]
        public string nv_nhiemvu { get; set; }
    }
}
