//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_chitiet
    {
        public int ct_id { get; set; }
        public int tour_id { get; set; }
        public int dd_id { get; set; }
        public int ct_thutu { get; set; }
    }
}
