//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tour_khachhang
    {
		[Display(Name = "Mã KH")]
        public int kh_id { get; set; }

        [Required]
        [Display(Name = "Tên khách hàng")]
        public string kh_ten { get; set; }

        [Required]
        [Display(Name = "Số điện thoại")]
        public string kh_sdt { get; set; }

        [Required]
        [Display(Name = "Ngày sinh"), DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime kh_ngaysinh { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string kh_email { get; set; }

        [Required]
        [Display(Name = "CMND")]
        public string kh_cmnd { get; set; }
    }
}
